### ISSUE TITLE
Image uploading says 'this field is required', uploads image anyway

### ISSUE THREAD

**Issue by christoball** [TNRIS/api.tnris.org#35]
@jwhaney 

When uploading images it returns errors 'this field is required' even though I'm choosing files and the images are being uploaded.

<img width="1098" alt="Screen Shot 2019-09-30 at 11 04 10 AM" src="https://user-images.githubusercontent.com/1877550/65896312-99f11000-e372-11e9-9cbf-e0ae04dbaf74.png">

Steps to reproduce:
- Select add image in dataset collection.
- Select file
- Select 'Add Another Image'
- Select file
- Press 'Save'
- Returns errors
- navigate back out and return to the dataset collection.
- The Images are uploaded, and if you tried to upload them again because it told you it didn't select any, you'll have multiple images (I didnt screen shot this)

**Comment by jwhaney** [comment]
just to document this for the future, I'm gonna tag this as a future enhancement but the current image upload and caption form is behaving as it is supposed to (see below image with helper text).

![Screenshot from 2019-09-30 11-48-10](https://user-images.githubusercontent.com/13525011/65899644-c4929700-e379-11e9-829b-f37cfeed09d9.png)

the image needs to exist before a caption can be added. this is a timing issue of sorts because if you add both a new image and its new corresponding caption text at the same time, you get a form validation error. the image does end up saved to s3 if you exit the collection then come back and look at the images, but the caption is not saved.

**Comment by adambreznicky** [comment]
workflow issue. resolved.
