### ISSUE TITLE
Updating Agency Details in Lore

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/api.tnris.org#4]
Hey y'all,

I created an agency on Lore called "CGS" and didn't really populate the about sections, because I wasn't totally sure what it was...now I do!

Can we please update the agency card to the following?

Name: National Geodetic Survey
Abbreviation: NGS
Media Type: Print
General Scale: 1:2000
About: Formerly the United States Coast and Geodetic Survey (USC&GS), is a federal agency that defines and manages a national coordinate system, providing the foundation for transportation, communication, mapping, and charting.  Since 1970, it has been part of the National Oceanic and Atmospheric Administration (NOAA).

@mitchellryant @JasonKleinert @christoball 

Let me know if you need anything else! Thanks!!

**Comment by christoball** [comment]
Can I make a suggestion on the 'about'? Add the name at the beginning. It's a little confusing if it just says its former name.

About: The National Geodetic Survey (NGS), formerly the United States Coast and Geodetic Survey (USC&GS), is a federal agency that defines and manages a national coordinate system, providing the foundation for transportation, communication, mapping, and charting. Since 1970, it has been part of the National Oceanic and Atmospheric Administration (NOAA).

**Comment by christoball** [comment]
Here's an image that can be used for datahub

![ngs_datahub](https://user-images.githubusercontent.com/1877550/59296331-5059a980-8c4b-11e9-9e14-a1a7cdfb5760.jpg)

**Comment by adambreznicky** [comment]
thanks for the image @christoball 
image has been uploaded to s3 and the agency table in datahub database has been updated with all the information y'all have provided.
excellent!
