### ISSUE TITLE
Thumbnail not appearing for RWPD Map Collection

### ISSUE THREAD

**Issue by christoball** [TNRIS/api.tnris.org#67]
@jwhaney @adambreznicky 
I was trying to change out the thumbnail image for the RWPD map collection to a more web optimized version. In the API backend it shows that the image is there, but it isn't showing on the front-end on https://www.tnris.org/maps/

The process I did was:
- Check 'delete thumbnail'
- Save and Continue editing
- 'Choose file' with my new file
- Save

**Comment by adambreznicky** [comment]
that is because the api for maps, collections, and historical collections are only refreshed once every hour. any changes made in the backend for these will be reflected in the api endpoints (or frontends) up to 1 hour after the change is made (actual time depends on when the change is made relatively to the next scheduled refresh). i manually just ran the refresh and your change is now reflected on the frontend as expected.
