### ISSUE TITLE
In-Line Images Upload for Lore Collections

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/api.tnris.org#75]
@adambreznicky  @jwhaney  @csidenblad 

Similar to Ortho collections, we would like the enhancement of adding a custom image to display in LORE to show in the "details" tab on DataHub.

**Comment by adambreznicky** [comment]
@LaurenKirk i think you mean the "preview" tab (rather than details) for viewing sample pictures of the data? 

----notes for dev---
should be able to use the same image table as the rest of the lcd collections?
will require enhancements to datahub also to advance the historical aerials template, preview tab, to not be hard coded with images based on the agency and, instead, use the api images

the api /historical/collections endpoint will need to be updated via the materialized view table sql. reference the code for the lcd endpoint. sql will need to be manually run within pgadmin.

**Comment by LaurenKirk** [comment]
@adambreznicky 

yep, the "preview" tab is what I was referring to.

**Comment by adambreznicky** [comment]
@LaurenKirk do you have a few specific collections in mind with images that are ready to go i could use to implement this?
to make this happen, it would be best if i could develop it with real examples.
if you could hook me up with a few collection uuid's and the images you'd like to use for them i can get started.

**Comment by adambreznicky** [comment]
resolved via commit fa368a8c83be9e574e7bf33f762a3054dd5f29f0
